import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  // Round 11 W11.7 (N3-R11-06): `dist-engine/` is the esbuild output for
  // the embedded CLI engine bundle. It's regenerated by `npm run
  // build:engine` and shipped into the CLI binary via include_str!,
  // never hand-edited. Ignoring keeps lint runs from flagging the
  // minified output.
  globalIgnores(["dist", "dist-engine", "src-tauri"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      // Aligned with tsconfig.app.json `target: es2023` — the TS parser
      // already accepts 2023 syntax, so keeping ESLint at 2020 produced a
      // mismatched signal about what the codebase is actually compiled as.
      ecmaVersion: 2023,
      globals: globals.browser,
    },
    rules: {
      // ESLint 10 + react-hooks 7 introduced this rule as an error. Five
      // sites in this codebase intentionally call setState inside useEffect
      // to clear transient UI status (e.g. last-action result, preview list,
      // error banner) when a dependency context changes — typically when
      // the user picks a different subtitle file. The textbook React-19
      // alternative is "remount via `key` prop on a wrapper component", but
      // for a status banner that's a heavier refactor than the pattern
      // warrants. The extra cascading render is one frame of work on a
      // tiny piece of state, not a perf concern. Keep the pattern; relax
      // the rule.
      //
      // Audit recipe — to find every set-state-in-effect site (and confirm
      // none are accidental new growth), grep:
      //
      //   rg -nU 'useEffect\([^)]*\{[^}]*\bset[A-Z]\w*\(' src --multiline
      //
      // The five legitimate sites all clear transient banners or preview
      // lists. Any new match should be reviewed for a `key`-based remount
      // alternative before being accepted.
      "react-hooks/set-state-in-effect": "off",

      // CSP guardrail: production CSP is `style-src 'self' 'unsafe-inline'`,
      // which React 19 needs because it serializes `style={{...}}` to inline
      // `style="..."` strings. Today no callsite passes user-controlled
      // text into `style={{ color: ..., background: ..., border: ... }}` —
      // grep confirms only `var(--token)` literals, hex colors, and pixel
      // values from controlled state. Future change passing
      // `style={{ color: someUserString }}` would re-introduce a CSS-
      // injection surface even with `connect-src 'none'` blocking fetch
      // (URL-parse side channels remain).
      //
      // This rule flags `style={{ key: <Identifier|MemberExpression|
      // CallExpression|TemplateLiteral> }}` — the four shapes that can
      // carry user text. ConditionalExpression and Literal are NOT
      // flagged: ternaries on internal state with literal branches
      // (`busy ? "var(--bg-input)" : "var(--accent)"`) are the dominant
      // pattern in this codebase and are safe by inspection. If a
      // future call-site needs a non-literal value and the value is
      // demonstrably not user-controlled, suppress the rule for that
      // line with `// eslint-disable-next-line no-restricted-syntax`
      // and add a WHY comment.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "JSXAttribute[name.name='style'] > JSXExpressionContainer > ObjectExpression > Property > Identifier.value",
          message:
            "style={{ ... }} value is an Identifier — possible user-controlled CSS injection. Use a literal or a ConditionalExpression with literal branches; if the identifier is provably static, suppress with an eslint-disable-next-line + WHY comment.",
        },
        {
          selector:
            "JSXAttribute[name.name='style'] > JSXExpressionContainer > ObjectExpression > Property > MemberExpression.value",
          message:
            "style={{ ... }} value is a MemberExpression — possible user-controlled CSS injection. Same opt-out as Identifier above.",
        },
        {
          selector:
            "JSXAttribute[name.name='style'] > JSXExpressionContainer > ObjectExpression > Property > CallExpression.value",
          message:
            "style={{ ... }} value is a CallExpression — possible user-controlled CSS injection. Same opt-out as Identifier above.",
        },
        {
          selector:
            "JSXAttribute[name.name='style'] > JSXExpressionContainer > ObjectExpression > Property > TemplateLiteral.value",
          message:
            "style={{ ... }} value is a TemplateLiteral — possible user-controlled CSS injection. Use a Literal or a ConditionalExpression with literal branches.",
        },
      ],
    },
  },
]);
